/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connection.ConnectionFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Funcionario;
import model.bean.Usuario;
import model.dao.FuncionarioDAO;
import model.dao.UsuarioDAO;

/**
 *
 * @author iagob
 */
public class Funcionarios extends javax.swing.JFrame {
    ConnectionFactory con = new ConnectionFactory();
    Funcionario func = new Funcionario();
    FuncionarioDAO dao = new FuncionarioDAO();
    Usuario user = new Usuario();
    UsuarioDAO userDao = new UsuarioDAO();
    
    
    public Funcionarios() {
        initComponents();
        ConnectionFactory.getConnection();
        DefaultTableModel modelo = (DefaultTableModel) jTableFuncionarios.getModel();
        jTableFuncionarios.setRowSorter(new TableRowSorter(modelo));
        readTable();
    }
    
    public boolean verificaCampos(){
                if (txtFuncNome.getText().equals("")
                || txtFuncUsuario.getText().equals("")
                || jFormattedTextFieldFuncCPF.getText().equals("   .   .   -  ")
                || jFormattedTextFieldFuncDataInicio.getText().equals("  /  /    ")
                || jPasswordFieldFuncSenha.getText().equals("")) return false;
                else {
                        return true;
                        }
    }
    public boolean verificaCamposAlterar(){
                if (txtFuncNome.getText().equals("")
                || txtFuncUsuario.getText().equals("")
                || jFormattedTextFieldFuncCPF.getText().equals("   .   .   -  ")
                || jFormattedTextFieldFuncDataInicio.getText().equals("  /  /    ")) return false;
                else {
                        return true;
                        }
    }
    
    public void readTable(){
        
        DefaultTableModel modelo = (DefaultTableModel)jTableFuncionarios.getModel();
        modelo.setNumRows(0);
        FuncionarioDAO fdao = new FuncionarioDAO();
        
        for (Funcionario func: fdao.listar()){
            
            modelo.addRow(new Object[]{
                func.getNome(),
                func.getCpf(),
                func.getDataInicio(),
                func.getUsuario(),
                func.getFuncao()
            });
            
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneFuncionarios = new javax.swing.JTabbedPane();
        jPanelMainFuncionarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jPanelCadFuncionarios = new javax.swing.JPanel();
        btnFuncCadastrar = new javax.swing.JButton();
        btnFuncEditar = new javax.swing.JButton();
        btnFuncExcluir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lblFuncDataInicio = new javax.swing.JLabel();
        txtFuncNome = new javax.swing.JTextField();
        jFormattedTextFieldFuncDataInicio = new javax.swing.JFormattedTextField();
        jFormattedTextFieldFuncCPF = new javax.swing.JFormattedTextField();
        btnFuncPesquisar = new javax.swing.JButton();
        btnFuncSalvar = new javax.swing.JButton();
        lblFuncUsuario = new javax.swing.JLabel();
        txtFuncUsuario = new javax.swing.JTextField();
        lblFuncSenha = new javax.swing.JLabel();
        jPasswordFieldFuncSenha = new javax.swing.JPasswordField();
        btnFuncCancelar = new javax.swing.JButton();
        btnFuncAlterar = new javax.swing.JButton();
        jRadioButtonFuncAtivo = new javax.swing.JRadioButton();
        jComboBoxCargo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFuncMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionarios");

        jTabbedPaneFuncionarios.setBackground(new java.awt.Color(0, 51, 255));

        jPanelMainFuncionarios.setBackground(new java.awt.Color(255, 255, 255));

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "DataInicio", "Usuario", "Função", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFuncionarios);

        javax.swing.GroupLayout jPanelMainFuncionariosLayout = new javax.swing.GroupLayout(jPanelMainFuncionarios);
        jPanelMainFuncionarios.setLayout(jPanelMainFuncionariosLayout);
        jPanelMainFuncionariosLayout.setHorizontalGroup(
            jPanelMainFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
        );
        jPanelMainFuncionariosLayout.setVerticalGroup(
            jPanelMainFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
        );

        jTabbedPaneFuncionarios.addTab("Funcionarios", jPanelMainFuncionarios);

        jPanelCadFuncionarios.setBackground(new java.awt.Color(255, 255, 255));

        btnFuncCadastrar.setText("Cadastrar");
        btnFuncCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncCadastrarActionPerformed(evt);
            }
        });

        btnFuncEditar.setText("Editar");
        btnFuncEditar.setEnabled(false);
        btnFuncEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncEditarActionPerformed(evt);
            }
        });

        btnFuncExcluir.setText("Excluir");
        btnFuncExcluir.setEnabled(false);
        btnFuncExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncExcluirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("CPF");

        lblFuncDataInicio.setText("Data de Inicio");

        txtFuncNome.setEnabled(false);

        try {
            jFormattedTextFieldFuncDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFuncDataInicio.setEnabled(false);
        jFormattedTextFieldFuncDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldFuncDataInicioActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldFuncCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnFuncPesquisar.setText("Pesquisar");
        btnFuncPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncPesquisarActionPerformed(evt);
            }
        });

        btnFuncSalvar.setText("Salvar");
        btnFuncSalvar.setVisible(false);
        btnFuncSalvar.setEnabled(false);
        btnFuncSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncSalvarActionPerformed(evt);
            }
        });

        lblFuncUsuario.setText("Usuario");

        txtFuncUsuario.setEnabled(false);

        lblFuncSenha.setText("Senha");

        jPasswordFieldFuncSenha.setEnabled(false);

        btnFuncCancelar.setText("Cancelar");
        btnFuncCancelar.setEnabled(false);
        btnFuncCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncCancelarActionPerformed(evt);
            }
        });

        btnFuncAlterar.setText("Alterar");
        btnFuncAlterar.setEnabled(false);
        btnFuncAlterar.setVisible(false);
        btnFuncAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncAlterarActionPerformed(evt);
            }
        });

        jRadioButtonFuncAtivo.setText("Ativo");
        jRadioButtonFuncAtivo.setEnabled(false);
        jRadioButtonFuncAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFuncAtivoActionPerformed(evt);
            }
        });

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caixa", "Gerente" }));
        jComboBoxCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCargoActionPerformed(evt);
            }
        });

        jLabel3.setText("Cargo: ");

        javax.swing.GroupLayout jPanelCadFuncionariosLayout = new javax.swing.GroupLayout(jPanelCadFuncionarios);
        jPanelCadFuncionarios.setLayout(jPanelCadFuncionariosLayout);
        jPanelCadFuncionariosLayout.setHorizontalGroup(
            jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnFuncCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFuncEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFuncExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnFuncPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                        .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldFuncCPF))
                            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFuncNome, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblFuncDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblFuncUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFuncUsuario)
                                    .addComponent(jFormattedTextFieldFuncDataInicio))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFuncSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButtonFuncAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordFieldFuncSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBoxCargo, 0, 124, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadFuncionariosLayout.createSequentialGroup()
                        .addComponent(btnFuncSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                                .addComponent(btnFuncAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadFuncionariosLayout.createSequentialGroup()
                                .addComponent(btnFuncCancelar)
                                .addGap(11, 11, 11))))))
        );
        jPanelCadFuncionariosLayout.setVerticalGroup(
            jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                        .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldFuncCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFuncNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFuncDataInicio)
                                    .addComponent(jFormattedTextFieldFuncDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonFuncAtivo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFuncUsuario)
                                    .addComponent(txtFuncUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFuncSenha)
                                    .addComponent(jPasswordFieldFuncSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCadFuncionariosLayout.createSequentialGroup()
                                .addComponent(btnFuncCadastrar)
                                .addGap(15, 15, 15)
                                .addComponent(btnFuncPesquisar)
                                .addGap(18, 18, 18)
                                .addComponent(btnFuncEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnFuncExcluir)))
                        .addGap(18, 18, 18)
                        .addComponent(btnFuncAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFuncSalvar)
                            .addComponent(btnFuncCancelar))
                        .addGap(28, 28, 28))))
        );

        jTabbedPaneFuncionarios.addTab("Cadastro Funcionarios", jPanelCadFuncionarios);

        jMenuFuncMenu.setText("Arquivo");

        jMenuItem1.setText("Voltar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFuncMenu.add(jMenuItem1);

        jMenuBar1.add(jMenuFuncMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneFuncionarios)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneFuncionarios)
        );

        setSize(new java.awt.Dimension(576, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnFuncPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncPesquisarActionPerformed
       if (jFormattedTextFieldFuncCPF.getText().trim().length()<14){
           JOptionPane.showMessageDialog(null, "Campo CPF em branco");
       }else {
       func.setCpf(jFormattedTextFieldFuncCPF.getText());
       Funcionario model = dao.pesquisarCpf(func);
       txtFuncNome.setText(model.getNome());
       txtFuncUsuario.setText(model.getUsuario());
       jFormattedTextFieldFuncDataInicio.setText(String.valueOf(func.getDataInicio()));
       btnFuncEditar.setEnabled(true);
       btnFuncExcluir.setEnabled(true);
       }  
    }//GEN-LAST:event_btnFuncPesquisarActionPerformed

    private void btnFuncCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncCadastrarActionPerformed
        txtFuncNome.setEnabled(true);
        jFormattedTextFieldFuncDataInicio.setEnabled(true);
        txtFuncUsuario.setEnabled(true);
        jPasswordFieldFuncSenha.setEnabled(true);
        jRadioButtonFuncAtivo.setEnabled(true);
        btnFuncSalvar.setVisible(true);
        btnFuncSalvar.setEnabled(true);
        btnFuncCancelar.setEnabled(true);
    }//GEN-LAST:event_btnFuncCadastrarActionPerformed

    private void btnFuncSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncSalvarActionPerformed
        verificaCampos();
        if (verificaCampos() == true){
        btnFuncSalvar.setVisible(true);
        func.setNome(txtFuncNome.getText());
        func.setCpf(jFormattedTextFieldFuncCPF.getText());
        func.setAtivo(true);
        func.setDataInicio(jFormattedTextFieldFuncDataInicio.getText());
        func.setUsuario(txtFuncUsuario.getText());
        func.setSenha(jPasswordFieldFuncSenha.getText());
        func.setFuncao((String) jComboBoxCargo.getSelectedItem());
        user.setLogin(txtFuncUsuario.getText());
        user.setSenha(jPasswordFieldFuncSenha.getText());
        user.setFuncao((String) jComboBoxCargo.getSelectedItem());
        userDao.save(user);
        dao.save(func);
        txtFuncNome.setEnabled(false);
        jFormattedTextFieldFuncDataInicio.setEnabled(false);
        txtFuncUsuario.setEnabled(false);
        jPasswordFieldFuncSenha.setEnabled(false);
        btnFuncSalvar.setEnabled(false);
        jRadioButtonFuncAtivo.setEnabled(false);
        txtFuncNome.setText("");
        txtFuncUsuario.setText("");
        jFormattedTextFieldFuncDataInicio.setText("");
        jPasswordFieldFuncSenha.setText("");
        btnFuncEditar.setEnabled(false);
        btnFuncExcluir.setEnabled(false);
        readTable();}
        else{
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
        }
    }//GEN-LAST:event_btnFuncSalvarActionPerformed

    private void btnFuncCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncCancelarActionPerformed
        txtFuncNome.setText("");
        txtFuncUsuario.setText("");
        jFormattedTextFieldFuncDataInicio.setText("");
        jPasswordFieldFuncSenha.setText("");
        txtFuncNome.setEnabled(false);
        jFormattedTextFieldFuncDataInicio.setEnabled(false);
        txtFuncUsuario.setEnabled(false);
        jPasswordFieldFuncSenha.setEnabled(false);
        jRadioButtonFuncAtivo.setEnabled(false);
        btnFuncSalvar.setEnabled(false);
        btnFuncSalvar.setVisible(false);
        btnFuncCancelar.setEnabled(false);
        btnFuncEditar.setEnabled(false);
        btnFuncExcluir.setEnabled(false);
    }//GEN-LAST:event_btnFuncCancelarActionPerformed

    private void btnFuncEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncEditarActionPerformed
        ConnectionFactory.getConnection();
        btnFuncAlterar.setVisible(true);
        btnFuncAlterar.setEnabled(true);
        btnFuncCancelar.setEnabled(true);
        txtFuncNome.setEnabled(true);
        jFormattedTextFieldFuncDataInicio.setEnabled(true);
        txtFuncUsuario.setEnabled(true);
        jRadioButtonFuncAtivo.setEnabled(true);
 
    }//GEN-LAST:event_btnFuncEditarActionPerformed

    private void btnFuncAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncAlterarActionPerformed
        verificaCamposAlterar();
        if (verificaCamposAlterar()== true){
        func.setNome(txtFuncNome.getText());
        func.setDataInicio(jFormattedTextFieldFuncDataInicio.getText());
        func.setUsuario(txtFuncUsuario.getText());
        dao.editar(func);
        txtFuncNome.setText("");
        txtFuncUsuario.setText("");
        jFormattedTextFieldFuncDataInicio.setText("");
        jPasswordFieldFuncSenha.setText("");
        txtFuncNome.setEnabled(false);
        jFormattedTextFieldFuncDataInicio.setEnabled(false);
        txtFuncUsuario.setEnabled(false);
        jRadioButtonFuncAtivo.setEnabled(false);
        jPasswordFieldFuncSenha.setEnabled(false);
        btnFuncSalvar.setEnabled(false);
        btnFuncCancelar.setEnabled(false);
        btnFuncEditar.setEnabled(false);
        btnFuncExcluir.setEnabled(false);
        readTable();}
        else{
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos");
        }
    }//GEN-LAST:event_btnFuncAlterarActionPerformed

    private void jFormattedTextFieldFuncDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFuncDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldFuncDataInicioActionPerformed

    private void jRadioButtonFuncAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFuncAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFuncAtivoActionPerformed

    private void btnFuncExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncExcluirActionPerformed
        func.setCpf(jFormattedTextFieldFuncCPF.getText());
        user.setLogin(txtFuncUsuario.getText());
        userDao.delete(user);
        dao.delete(func);
        txtFuncNome.setText("");
        txtFuncUsuario.setText("");
        jFormattedTextFieldFuncDataInicio.setText("");
        jPasswordFieldFuncSenha.setText("");
        txtFuncNome.setEnabled(false);
        jFormattedTextFieldFuncDataInicio.setEnabled(false);
        txtFuncUsuario.setEnabled(false);
        jRadioButtonFuncAtivo.setEnabled(false);
        jPasswordFieldFuncSenha.setEnabled(false);
        btnFuncSalvar.setEnabled(false);
        btnFuncCancelar.setEnabled(false);
        btnFuncEditar.setEnabled(false);
        btnFuncExcluir.setEnabled(false);
        readTable();
    }//GEN-LAST:event_btnFuncExcluirActionPerformed

    private void jComboBoxCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCargoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFuncAlterar;
    private javax.swing.JButton btnFuncCadastrar;
    private javax.swing.JButton btnFuncCancelar;
    private javax.swing.JButton btnFuncEditar;
    private javax.swing.JButton btnFuncExcluir;
    private javax.swing.JButton btnFuncPesquisar;
    private javax.swing.JButton btnFuncSalvar;
    private javax.swing.JComboBox<String> jComboBoxCargo;
    private javax.swing.JFormattedTextField jFormattedTextFieldFuncCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldFuncDataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFuncMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelCadFuncionarios;
    private javax.swing.JPanel jPanelMainFuncionarios;
    private javax.swing.JPasswordField jPasswordFieldFuncSenha;
    private javax.swing.JRadioButton jRadioButtonFuncAtivo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPaneFuncionarios;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JLabel lblFuncDataInicio;
    private javax.swing.JLabel lblFuncSenha;
    private javax.swing.JLabel lblFuncUsuario;
    private javax.swing.JTextField txtFuncNome;
    private javax.swing.JTextField txtFuncUsuario;
    // End of variables declaration//GEN-END:variables
}
